version: '3.7'
name: same
networks:
  redpanda_network:
    driver: bridge
volumes:
  redpanda: null
services:

  kafka:
    image: docker.redpanda.com/vectorized/redpanda:v22.3.11
    command:
      - redpanda start
      - --smp 1
      - --overprovisioned
      - --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://kafka:29092,OUTSIDE://localhost:9092
      - --pandaproxy-addr 0.0.0.0:8082
      - --advertise-pandaproxy-addr localhost:8082
    ports:
      - 8081:8081 # Schema Registry
      - 8082:8082 # Pandaproxy
      - 9092:9092 # Kafka
      - 9644:9644 # Admin API
      - 29092:29092 # Kafka (outside)
